doc2docx handler.
Bnei-Baruch/archive-unzip pull request #5
Opened 2018-11-05 05:52 UTC by bbfsdev

2018-11-30 03:27 UTC, edoshor requested changes

2018-11-30 03:27 UTC, edoshor commented on app/doc2html/conversionFunctions.py
> +                stdout, stderr = p.communicate(timeout=30)
Can we make `timeout`a function of the number of files ?
Something like `min(60, max(10, number of files))`

2018-11-30 03:27 UTC, edoshor commented on app/doc2html/conversionFunctions.py
> +        logger.debug("Failed or timedout when trying to lock soffice.")
Make it error level log entry
This message is a bit misleading as this except block is handling more then just locking problems.

2018-11-30 03:27 UTC, edoshor commented on app/doc2html/views.py
> +        file_type = get_file_type(uid)
This is a classic N+1 problem. please call the DB only once, you call it in a loop...

2018-11-30 03:27 UTC, edoshor commented on app/doc2html/views.py
> +                current_app.logger.debug('Failed urlretrieve for %s' % url)
`urlretrieve` is not so meaningful, try something in English

2018-11-30 03:27 UTC, edoshor commented on app/doc2html/views.py
> +                return ret
one error kills entire batch ?

2018-11-30 03:27 UTC, edoshor commented on app/doc2html/views.py
> +    uid_first_dir = get_and_create_dir(uids[0])
use a temp dir.

2018-12-12 16:51 UTC, bbfsdev commented on app/doc2html/conversionFunctions.py
> +                stdout, stderr = p.communicate(timeout=30)
Done.

2018-12-12 18:08 UTC, bbfsdev commented on app/doc2html/conversionFunctions.py
> +        logger.debug("Failed or timedout when trying to lock soffice.")
Timeout is not an error, it is 503. Warning.

2019-01-01 02:33 UTC, closed without merging